name: FW360
favicon: null
layout_spectrum: 0.67919
typography_spectrum: 0.74567
title: Fieldwork 360
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6d6e71'
    - '#a4c2f4'
    - '#ffffff'
    - '#000000'
    - '#00ff00'
  brandStrength: 0.1875
  lightness: 0.3125
  saturation: 0.625
  rhythmicContrast: 0.1644517877139151
purpose: []
