name: FW360
favicon: null
layout_spectrum: 0.68496
typography_spectrum: 0.059216099325567484
title: Fieldwork 360
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6d6e71'
    - '#8cc63f'
    - '#92db24'
    - '#00ff00'
    - '#8bd12e'
  brandStrength: 0.125
  lightness: 0.10917627019807696
  saturation: 0.6875
  rhythmicContrast: 0.1644517877139151
purpose: []
