name: FW360
favicon: null
layout_spectrum: 0.7363904449157417
typography_spectrum: 0.059216099325567484
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.04187366412952542
  lightness: 0.10917627019807696
  saturation: 0.7175215256866068
  rhythmicContrast: 0.1644517877139151
purpose: []
